import Link from 'next/link';

export const metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
}
export default function AboutPage() {
  return (
    <Link href="/">Go To Home</Link>
  )
}
