import Link from 'next/link'

export const metadata = {
  title: 'CFSC - Contact Page',
  description: 'Generated by create next app',
}
export default function ContactPage() {
  return (
    <div>
      <Link href="/">Go To Home</Link>
      <h1>Contact Page</h1>
    </div>
  )
}
