import Link from 'next/link';

export const metadata = {
  title: 'CFSC - FQA Page',
  description: 'Generated by create next app',
}
export default function FQAPage() {
  return (
    <div>
      <Link href="/">Go To Home</Link>
      <h1>FQA Page</h1>
      <h1>Những Câu hỏi thường gặp ?</h1>
    </div>
  )
}
