import Link from 'next/link';

export const metadata = {
  title: 'CFSC - Project Page',
  description: 'Generated by create next app',
}
export default function ProjectPage() {
  return (
    <div>
      <Link href="/">Go To Home</Link>
      <h1>Project Page</h1>
    </div>
  )
}
